spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kursovayaa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true